//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDS.Data.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlantMaster
    {
        public int PlantID { get; set; }
        public string PlantName { get; set; }
        public string PlantName_PressSpecification { get; set; }
        public string Location { get; set; }
        public Nullable<byte> UnitSystemId { get; set; }
        public Nullable<byte> LengthUnit { get; set; }
        public Nullable<byte> PressureUnit { get; set; }
        public Nullable<double> HeadCount { get; set; }
        public Nullable<double> FringeWageRate { get; set; }
        public Nullable<double> HourlyWageRate { get; set; }
        public Nullable<double> StdPerfomanceGoal { get; set; }
        public Nullable<double> AllPerformanceGoal { get; set; }
        public Nullable<double> StdReliefDivisor { get; set; }
        public Nullable<double> StdQuotedWeek { get; set; }
        public Nullable<double> MoldingManning { get; set; }
        public Nullable<double> DefaultUTLZPercentage { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string InjectionMoldingAreaId { get; set; }
        public string PlantName_QAD { get; set; }
        public string PlantColor { get; set; }
        public Nullable<int> SaasId { get; set; }
    
        public virtual CountryMaster CountryMaster { get; set; }
        public virtual RegionMaster RegionMaster { get; set; }
    }
}
