//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDS.Data.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class RightsMaster
    {
        public long RightId { get; set; }
        public string ModuleName { get; set; }
        public string SubmoduleName { get; set; }
        public string FunctionName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<double> ModuleSortOrder { get; set; }
        public Nullable<double> SubModuleSortOrder { get; set; }
        public Nullable<double> FunctionSortOrder { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
